version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:1.35.0
    steps:
      - checkout
      - run: git config --global --unset "url.ssh://git@github.com.insteadof" || true
      - run: sudo apt-get update && sudo apt-get install openjdk-11-jdk
      - run: make java